name: escape_handler
version: 0.0.3
authors:
- Nikolaus Graf <nik@blossom.io>
- Allan Berger <allan@blossom.io>
description: An easy-to-use library for managing widget behaviour when the ESC keyboard event is fired.
homepage: https://github.com/blossom/escape-handler-dart
environment:
  sdk: '>=0.8.10+6 <2.0.0'
dev_dependencies:
  unittest: '>=0.9.0 <0.10.0'
